In [1]:
import numpy as np
from cpso_particle import COMB_Particle
from cpso_swarm import COMB_Swarm

In [2]:
npart = 2
c1 = 2.1
c2 = 2.2
c3 = 2.3
ndim = 190
alpha = 0.5
test_size = 0.3
x_bounds = (-6.0, 6.0)
v_bounds = (-4.0, 0.25)
w_bounds = (0.4, 0.9)
t_bounds = (0, 3)
data_path = 'working_data/prepped_for_classifier/data.csv'
target_path = 'working_data/prepped_for_classifier/target.csv'

In [3]:
swarm = COMB_Swarm(npart, c1, c2, c3, ndim, alpha, test_size,
                   x_bounds, v_bounds, w_bounds, t_bounds,
                   data_path, target_path)

That's good, the `__init__` method didn't raise any errors.

In [4]:
swarm.npart

2

In [5]:
swarm.c1

2.1

In [6]:
swarm.c2

2.2

In [7]:
swarm.c3

2.3

In [8]:
swarm.ndim

190

In [9]:
swarm.alpha

0.5

In [10]:
swarm.x_bounds

(-6.0, 6.0)

In [11]:
swarm.v_bounds

(-4.0, 0.25)

In [12]:
swarm.w_bounds

(0.4, 0.9)

In [13]:
swarm.t_bounds

(0, 3)

In [14]:
swarm.gbest

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [15]:
swarm.gbest_counter

0

In [16]:
swarm.gbinary

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [17]:
swarm.g_fitness

0.0

In [18]:
swarm.abest

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [19]:
swarm.abinary

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [20]:
swarm.a_fitness

0.0

In [21]:
swarm.swarm

[]

In [22]:
swarm.clf

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [23]:
swarm.data

array([[22.025, 15.45 ,  0.   , ...,  0.165, 62.31 ,  0.   ],
       [94.97 , 91.785,  0.   , ...,  0.   , 39.89 ,  0.   ],
       [ 0.   ,  0.   ,  0.   , ...,  5.685,  3.09 ,  0.   ],
       ...,
       [ 3.73 ,  4.64 ,  0.26 , ...,  3.72 ,  2.41 ,  0.   ],
       [ 8.44 ,  4.49 ,  0.9  , ...,  2.82 ,  2.03 ,  3.89 ],
       [ 0.   ,  0.16 ,  0.   , ...,  2.21 ,  3.03 ,  0.   ]])

In [24]:
swarm.data.shape

(256, 190)

In [25]:
swarm.target

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [26]:
swarm.target.shape

(256,)

In [27]:
swarm.X_train

array([[2.5700e+00, 2.8600e+00, 1.2600e+00, ..., 3.8800e+00, 2.5700e+00,
        2.3600e+00],
       [7.6855e+01, 4.1450e+01, 0.0000e+00, ..., 8.7300e+00, 4.7175e+01,
        3.8350e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 2.4800e+00, 2.1200e+00,
        0.0000e+00],
       ...,
       [3.1200e+00, 2.1700e+00, 6.6000e-01, ..., 1.5900e+00, 2.1800e+00,
        0.0000e+00],
       [3.5100e+00, 2.2000e+00, 0.0000e+00, ..., 1.5500e+00, 2.9300e+00,
        2.7600e+00],
       [7.0600e+00, 4.1300e+00, 7.0000e-02, ..., 4.3000e-01, 3.6400e+00,
        1.7900e+00]])

In [28]:
swarm.X_train.shape

(179, 190)

In [29]:
swarm.y_train

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0], dtype=int8)

In [30]:
swarm.y_train.shape

(179,)

In [31]:
swarm.X_test

array([[6.03, 5.73, 2.32, ..., 2.35, 3.59, 2.51],
       [0.  , 0.  , 0.  , ..., 2.24, 2.17, 0.  ],
       [2.59, 2.56, 1.37, ..., 0.  , 6.79, 0.  ],
       ...,
       [5.34, 6.5 , 0.53, ..., 1.52, 2.59, 0.  ],
       [4.06, 2.48, 0.11, ..., 3.67, 5.64, 2.71],
       [2.32, 1.72, 1.09, ..., 1.85, 3.05, 0.  ]])

In [32]:
swarm.X_test.shape

(77, 190)

In [33]:
swarm.y_test

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0], dtype=int8)

In [34]:
swarm.y_test.shape

(77,)

In [35]:
swarm.final_scores

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

So far so good. All the basic attribute assignments appear to have worked successfully. However, I still need to initialize my particles.

In [36]:
swarm.initialize_particles()

Oops. In my `eval_fitness()` method, it calls the class method, `test_classify()` without using self.

I forgot that I set small, workable parameters that didn't match the data I passed it. I need to generate some throwaway data of a suitable size.

I'm running into a host of issues because my trash, test data is so unlike what the code is designed for. I'm going to just use the working data and see what happens.

That's good, my initialize particles didn't raise any errors.

In [37]:
swarm.swarm

In [38]:
swarm.swarm[0]

In [39]:
attr = ['x', 'v', 'b', 'pbest', 'pbinary', 'p_fitness', 'w', 'c1', 'c2', 'c3', 'ndim', 'x_bounds', 'v_bounds', 'w_bounds']

In [40]:
for a in attr:
    print('{:12} : {}'.format(a, str(getattr(swarm.swarm[0], a))))
    print('\n' + '-'*80 + '\n')

x            : [-4.83469318 -0.12564644 -5.95274    -4.90318572  0.18436723  4.29315706
  1.52704275 -4.48632171  4.90080044  3.48213919  4.63310566 -0.8640174
  0.68311204 -4.1838073   0.78999567 -1.19930621  5.92044179  5.56122338
  2.88683034  0.71653616 -5.82107945 -3.86154864 -3.99117541 -3.03329265
  0.53087105  3.07601628  4.47194369 -0.04574039  5.65360779  5.23601855
 -1.29513898  0.53190714 -3.21196718 -2.43650971 -0.14146175 -3.80563168
  1.83753011  1.6982728  -0.40951044 -3.06392049 -2.51203685  4.47350215
 -1.97852571  0.02538952  2.17513278  2.44054265 -5.0781355  -2.6515233
 -2.32833373 -1.00273333 -3.77844854  3.68383184 -0.08132073 -3.12893351
 -1.41756166 -4.87622391 -5.09552329 -4.25163984 -5.28238184 -0.05466832
 -2.90284165  4.52660097 -5.39231822 -5.18893291  3.08623519 -3.97475235
 -1.91902771 -2.43799419  2.74138478  5.28213571  2.10288713  0.0269968
  3.24084972  1.80663372  4.40315013  2.26625775  0.04595618  4.0201632
  0.78352728  1.37234677 -1.67284306  4.

At a glance, that all looks good. I tested COMB_Particle already so I won't do much thorough testing, but it looks like everything propagated correctly. w should still be 0, because it is initialized in the first run of the actual algorithm in `execute_search()`. I'll double check that all the position vectors are independent copies and not references to the same location.

In [41]:
(swarm.swarm[0].x == swarm.swarm[0].pbest).all()

True

In [42]:
(swarm.swarm[0].b == swarm.swarm[0].pbinary).all()

True

In [43]:
swarm.swarm[0].x[0]

-4.834693176824778

In [44]:
swarm.swarm[0].x[0] = 0

In [45]:
(swarm.swarm[0].x == swarm.swarm[0].pbest).all()

False

In [46]:
swarm.swarm[0].b[0]

False

In [47]:
swarm.swarm[0].b[0] = False

In [48]:
(swarm.swarm[0].b == swarm.swarm[0].pbinary).all()

True

In [49]:
swarm.swarm[0].x[0] = 5.123637298457574
swarm.swarm[0].b[0] = True

In [50]:
(swarm.swarm[0].x == swarm.swarm[0].pbest).all()

False

In [51]:
(swarm.swarm[0].b == swarm.swarm[0].pbinary).all()

False

Looks good to me. Let's check the other particle and make sure it is different.

In [52]:
swarm.swarm[1]

In [53]:
for a in attr:
    print('{:12} : {}'.format(a, str(getattr(swarm.swarm[1], a))))
    print('\n' + '-'*80 + '\n')

x            : [-4.26657389 -0.80248806  5.30982007 -1.25701206  0.49101063  1.03595483
  1.28222388 -0.02213334  4.61291803  3.05210923 -2.49218515  1.53570143
 -3.21659276 -5.04540504  0.64519629 -5.58717568 -2.02567476  3.13442513
  1.81074367  2.6263566   1.18677789 -2.46856535 -4.79176278 -4.86433974
  2.62343566 -2.33065016  2.694799    0.07356595  3.59898785  2.35759959
 -1.30895696 -1.01827279 -5.14650989  2.17667887  5.73696182  2.23971511
 -2.84360357 -3.02159088  0.12496169 -5.49355612  0.66034876  0.93167774
 -0.68208462 -2.47742721  4.84320031 -3.70098343 -0.30573742  2.25917676
  5.38077632 -5.39392931 -3.75647615  4.95476301 -2.04228945  2.84447188
  1.89284095  2.38692485 -2.33037199 -3.52257589 -1.35747308 -1.13088831
  2.76557418  2.3880455  -2.78419917 -5.28326983  0.03297823  0.95789423
 -4.86049944  0.62028322  2.454732    4.43825885 -5.62947022 -5.39338918
 -1.89180229  1.95810755  3.67809066 -2.52636918  5.41480754 -0.77396689
 -3.92786523  2.998001    0.40534753

Again this all looks reasonable. Sanity checks are all good. Everything that should be different from the first particle is different and everything that shouldn't be different is the same.

In [54]:
(swarm.swarm[1].x == swarm.swarm[1].pbest).all()

True

In [55]:
(swarm.swarm[1].b == swarm.swarm[1].pbinary).all()

True

In [56]:
swarm.swarm[1].x[0]

-4.266573889171991

In [57]:
swarm.swarm[1].x[0] = 0

In [58]:
(swarm.swarm[1].x == swarm.swarm[1].pbest).all()

False

In [59]:
swarm.swarm[1].b[0]

False

In [60]:
swarm.swarm[1].b[0] = True

In [61]:
(swarm.swarm[1].b == swarm.swarm[1].pbinary).all()

False

In [62]:
swarm.swarm[1].x[0] = -3.2698038841035957
swarm.swarm[1].b[0] = False

In [63]:
(swarm.swarm[1].x == swarm.swarm[1].pbest).all()

False

In [64]:
(swarm.swarm[1].b == swarm.swarm[1].pbinary).all()

True

Again, all these sanity checks seem to work. I'm not testing very rigorously because I trust the internal workings of the COMB_Particle class based on a previous testing session.

Things that I am not sure if they worked or not: `eval_fitness()`

In [65]:
swarm.gbest

array([-4.26657389, -0.80248806,  5.30982007, -1.25701206,  0.49101063,
        1.03595483,  1.28222388, -0.02213334,  4.61291803,  3.05210923,
       -2.49218515,  1.53570143, -3.21659276, -5.04540504,  0.64519629,
       -5.58717568, -2.02567476,  3.13442513,  1.81074367,  2.6263566 ,
        1.18677789, -2.46856535, -4.79176278, -4.86433974,  2.62343566,
       -2.33065016,  2.694799  ,  0.07356595,  3.59898785,  2.35759959,
       -1.30895696, -1.01827279, -5.14650989,  2.17667887,  5.73696182,
        2.23971511, -2.84360357, -3.02159088,  0.12496169, -5.49355612,
        0.66034876,  0.93167774, -0.68208462, -2.47742721,  4.84320031,
       -3.70098343, -0.30573742,  2.25917676,  5.38077632, -5.39392931,
       -3.75647615,  4.95476301, -2.04228945,  2.84447188,  1.89284095,
        2.38692485, -2.33037199, -3.52257589, -1.35747308, -1.13088831,
        2.76557418,  2.3880455 , -2.78419917, -5.28326983,  0.03297823,
        0.95789423, -4.86049944,  0.62028322,  2.454732  ,  4.43

In [66]:
swarm.g_fitness

0.6102081183350534

In [67]:
swarm.gbest_counter

0

In [68]:
swarm.gbinary

array([False, False,  True,  True, False,  True,  True, False,  True,
        True, False,  True, False, False,  True, False, False,  True,
        True,  True, False, False, False, False,  True, False,  True,
        True,  True,  True, False, False, False, False,  True,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True, False,
       False,  True,  True, False, False,  True,  True, False, False,
       False, False,  True, False,  True, False, False,  True,  True,
        True,  True, False, False, False, False,  True,  True, False,
        True,  True,  True,  True, False, False, False,  True, False,
       False,  True,  True,  True, False, False, False, False,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
        True, False,

In [69]:
swarm.abest

array([-4.26657389, -0.80248806,  5.30982007, -1.25701206,  0.49101063,
        1.03595483,  1.28222388, -0.02213334,  4.61291803,  3.05210923,
       -2.49218515,  1.53570143, -3.21659276, -5.04540504,  0.64519629,
       -5.58717568, -2.02567476,  3.13442513,  1.81074367,  2.6263566 ,
        1.18677789, -2.46856535, -4.79176278, -4.86433974,  2.62343566,
       -2.33065016,  2.694799  ,  0.07356595,  3.59898785,  2.35759959,
       -1.30895696, -1.01827279, -5.14650989,  2.17667887,  5.73696182,
        2.23971511, -2.84360357, -3.02159088,  0.12496169, -5.49355612,
        0.66034876,  0.93167774, -0.68208462, -2.47742721,  4.84320031,
       -3.70098343, -0.30573742,  2.25917676,  5.38077632, -5.39392931,
       -3.75647615,  4.95476301, -2.04228945,  2.84447188,  1.89284095,
        2.38692485, -2.33037199, -3.52257589, -1.35747308, -1.13088831,
        2.76557418,  2.3880455 , -2.78419917, -5.28326983,  0.03297823,
        0.95789423, -4.86049944,  0.62028322,  2.454732  ,  4.43

In [70]:
swarm.a_fitness

0.6102081183350534

In [71]:
swarm.abinary

array([False, False,  True,  True, False,  True,  True, False,  True,
        True, False,  True, False, False,  True, False, False,  True,
        True,  True, False, False, False, False,  True, False,  True,
        True,  True,  True, False, False, False, False,  True,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True, False,
       False,  True,  True, False, False,  True,  True, False, False,
       False, False,  True, False,  True, False, False,  True,  True,
        True,  True, False, False, False, False,  True,  True, False,
        True,  True,  True,  True, False, False, False,  True, False,
       False,  True,  True,  True, False, False, False, False,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
        True, False,

Those look correct. I manually matched them to the 1st particle in the list, which certainly has a higher fitness reported by `eval_fitness()` so this assignment of the global and archived bests appears to be working.

In [72]:
swarm.gbest_counter = 3
swarm.shuffle_gbest()

In [73]:
swarm.gbest

array([-0.24967007,  1.05491736, -5.32842393, -0.01689856,  3.49328427,
       -3.51339146,  2.83301602, -2.11701832, -4.55706486, -3.88682442,
        0.745835  , -1.89742288, -0.6004558 , -5.13154512, -2.93527136,
       -3.48032912, -0.25012708, -0.92242358,  5.71294586, -3.26733598,
       -3.79655016,  0.04395053,  4.07116596, -2.51011328, -2.94686382,
        5.9373889 , -0.49012684, -1.25115636, -2.30543019,  2.02903163,
       -5.01969855, -3.32268679,  1.60390889,  1.64365586,  2.47446828,
        2.01479941,  2.96374183, -1.45590338,  2.70349298,  0.57729976,
        4.47962468, -2.15555487, -0.80750538,  5.77596172,  0.9162143 ,
        2.61152916,  4.00432243, -0.67507243,  3.92353344, -2.47421542,
        1.11470691, -4.04790712, -2.72889041,  1.27288988, -2.24681544,
        3.80394051, -0.97248903, -5.77182912, -0.49540006,  4.32900735,
       -0.40186727,  0.5048731 , -4.0356437 ,  2.17763343,  2.78087568,
        2.3127712 , -5.21885242, -3.97625007, -2.10593352,  2.30

In [74]:
swarm.g_fitness

0.620734434124527

In [75]:
swarm.gbest_counter

0

In [76]:
swarm.gbinary

array([False,  True, False,  True,  True, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False, False,  True, False, False,  True,  True,
       False, False,  True, False, False,  True,  True, False,  True,
        True, False,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True, False, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
        True,  True,  True, False, False,  True,  True, False,  True,
        True,  True, False, False,  True,  True,  True, False, False,
       False,  True,  True, False, False,  True,  True, False,  True,
        True,  True, False, False, False, False,  True, False, False,
       False, False,  True, False,  True,  True,  True, False, False,
       False,  True, False,  True, False, False, False, False,  True,
        True, False,  True, False,  True,  True, False, False, False,
        True, False,

In [77]:
swarm.abest

array([-0.24967007,  1.05491736, -5.32842393, -0.01689856,  3.49328427,
       -3.51339146,  2.83301602, -2.11701832, -4.55706486, -3.88682442,
        0.745835  , -1.89742288, -0.6004558 , -5.13154512, -2.93527136,
       -3.48032912, -0.25012708, -0.92242358,  5.71294586, -3.26733598,
       -3.79655016,  0.04395053,  4.07116596, -2.51011328, -2.94686382,
        5.9373889 , -0.49012684, -1.25115636, -2.30543019,  2.02903163,
       -5.01969855, -3.32268679,  1.60390889,  1.64365586,  2.47446828,
        2.01479941,  2.96374183, -1.45590338,  2.70349298,  0.57729976,
        4.47962468, -2.15555487, -0.80750538,  5.77596172,  0.9162143 ,
        2.61152916,  4.00432243, -0.67507243,  3.92353344, -2.47421542,
        1.11470691, -4.04790712, -2.72889041,  1.27288988, -2.24681544,
        3.80394051, -0.97248903, -5.77182912, -0.49540006,  4.32900735,
       -0.40186727,  0.5048731 , -4.0356437 ,  2.17763343,  2.78087568,
        2.3127712 , -5.21885242, -3.97625007, -2.10593352,  2.30

In [78]:
swarm.a_fitness

0.620734434124527

In [79]:
swarm.abinary

array([False,  True, False,  True,  True, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False, False,  True, False, False,  True,  True,
       False, False,  True, False, False,  True,  True, False,  True,
        True, False,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True, False, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
        True,  True,  True, False, False,  True,  True, False,  True,
        True,  True, False, False,  True,  True,  True, False, False,
       False,  True,  True, False, False,  True,  True, False,  True,
        True,  True, False, False, False, False,  True, False, False,
       False, False,  True, False,  True,  True,  True, False, False,
       False,  True, False,  True, False, False, False, False,  True,
        True, False,  True, False,  True,  True, False, False, False,
        True, False,

Proofreading the code, it seems to do what I expect. This one is harder to prove, but the behavior appears to work. I will go back up to the cell containing a call to `shuffle_gbest()` and keep manually calling it until I get a fitness that is greater than a_fitness so I can see if abest updates to match the new gbest.

I manually called it until I got tired of it and it didn't ever randomly come up with a position better than the first abest, so I'm going to manually change a_fitness to force the call.

In [80]:
swarm.a_fitness = 0.5

In [81]:
swarm.gbest_counter = 3
swarm.shuffle_gbest()

In [82]:
swarm.gbest

array([-0.89548984,  4.27828476,  0.18190285, -5.59129099,  0.35530751,
       -1.70718218, -1.6995303 , -5.73225082, -3.2312693 ,  0.27360047,
        2.93877164,  3.17173582,  5.1047381 , -1.43369749,  3.64202493,
        1.65109308, -5.33410354,  1.73185299, -3.18940122, -1.26336789,
        3.79744951,  1.64494468,  4.53873716,  3.36829262,  1.00313702,
        5.33826594, -4.87145536, -5.17732065, -3.37494367, -0.17924554,
        1.84521983,  1.73325079, -1.69154755,  0.38357324,  3.04907678,
       -4.99137936,  5.76892482,  3.20032772, -4.49506352,  3.83252892,
       -0.72884994,  3.77782239, -1.11222091,  2.16212381, -3.87216403,
       -1.48537954, -0.18333872,  1.93887488,  5.26857342, -5.99800775,
       -5.14553157, -1.68182479, -4.6769561 , -5.50247109, -3.7522893 ,
        0.70260385,  4.21894762,  0.03593745, -3.57067142,  3.38680258,
       -4.82595828,  3.55269888, -1.73384439, -2.73660798, -2.86150069,
       -5.69114179,  3.47481186,  3.40950687, -0.6627815 ,  3.99

In [83]:
swarm.g_fitness

0.639155486756106

In [84]:
swarm.gbest_counter

0

In [85]:
swarm.gbinary

array([False,  True, False, False,  True, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True,  True,  True, False, False,  True, False,
        True,  True, False,  True,  True,  True, False,  True, False,
       False,  True, False,  True, False, False, False, False, False,
       False, False,  True,  True, False,  True, False,  True, False,
       False, False, False,  True,  True, False,  True, False,  True,
       False, False, False, False,  True,  True, False, False, False,
       False, False,  True, False, False,  True, False,  True,  True,
       False,  True, False, False,  True, False, False,  True,  True,
       False,  True, False,  True, False,  True, False,  True,  True,
       False,  True, False, False,  True, False, False, False,  True,
        True, False, False, False,  True, False, False, False,  True,
        True, False,

In [86]:
swarm.abest

array([-0.89548984,  4.27828476,  0.18190285, -5.59129099,  0.35530751,
       -1.70718218, -1.6995303 , -5.73225082, -3.2312693 ,  0.27360047,
        2.93877164,  3.17173582,  5.1047381 , -1.43369749,  3.64202493,
        1.65109308, -5.33410354,  1.73185299, -3.18940122, -1.26336789,
        3.79744951,  1.64494468,  4.53873716,  3.36829262,  1.00313702,
        5.33826594, -4.87145536, -5.17732065, -3.37494367, -0.17924554,
        1.84521983,  1.73325079, -1.69154755,  0.38357324,  3.04907678,
       -4.99137936,  5.76892482,  3.20032772, -4.49506352,  3.83252892,
       -0.72884994,  3.77782239, -1.11222091,  2.16212381, -3.87216403,
       -1.48537954, -0.18333872,  1.93887488,  5.26857342, -5.99800775,
       -5.14553157, -1.68182479, -4.6769561 , -5.50247109, -3.7522893 ,
        0.70260385,  4.21894762,  0.03593745, -3.57067142,  3.38680258,
       -4.82595828,  3.55269888, -1.73384439, -2.73660798, -2.86150069,
       -5.69114179,  3.47481186,  3.40950687, -0.6627815 ,  3.99

In [87]:
swarm.a_fitness

0.639155486756106

In [88]:
swarm.abinary

array([False,  True, False, False,  True, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True,  True,  True, False, False,  True, False,
        True,  True, False,  True,  True,  True, False,  True, False,
       False,  True, False,  True, False, False, False, False, False,
       False, False,  True,  True, False,  True, False,  True, False,
       False, False, False,  True,  True, False,  True, False,  True,
       False, False, False, False,  True,  True, False, False, False,
       False, False,  True, False, False,  True, False,  True,  True,
       False,  True, False, False,  True, False, False,  True,  True,
       False,  True, False,  True, False,  True, False,  True,  True,
       False,  True, False, False,  True, False, False, False,  True,
        True, False, False, False,  True, False, False, False,  True,
        True, False,

That definitely worked!

I don't need to check `convert_pos_to_binary()` because it is a copy of the method in the COMB_Particle class.

`eval_fitness()` is mostly dependent on `test_classify()`. However, the actual fitness function can be check to make sure all my parentheses are in the right place, etc. I also should check that the `np.count_nonzero()` function is doing what I expect. I think I chose it while the binary arrays were still int arrays where members were in {0, 1}. Now they're booleans. I expect, it should still be good.

In [89]:
testa = np.array([True, False, True, True, False])

In [90]:
np.count_nonzero(testa)

3

That works fine.

In [91]:
def test_eval_fitness(b):
    clf_perf = 0.5
    f = ((alpha*clf_perf)
         + (   (1-alpha)
             * ((ndim-np.count_nonzero(b)) / ndim)
           )
        )
    return f

In [92]:
alpha = 0.2
ndim = 5

This should give f = 0.2 * 0.5 + (1-0.2) * ((5 - 3)/5) = 0.42

In [93]:
test_eval_fitness(testa)

0.42000000000000004

Excellent, the 4 at the end is almost certainly a floating point error. The equation does what I want it to do. Now I just have to test `test_classify()` to make sure that it is returning what I want it to.

`test_classify()` is a very simple method. It runs a 10-fold cross validation on the feature subset it is passed and returns the mean of the 10 scores. Almost all of the work is hidden in an sklearn method. I'll triple check the documentation of the method I'm using, and manually ensure that the correct feature subset is being used.

`cross_val_score()` takes 3 positional arguments and a number of named arguments.
The first positional argument, `estimator`, is an estimator object implementing `fit` and is used to predict the data. I double checked with the `sklearn.svm.SVC` class, and it does implement `fit`. The second positional argument, `X`, is an array-like object that holds the data to fit. I'm passing a slice of the training data, `X_train`, created by the boolean array, `b`, that is being given to it. I need to double check that this syntax is producing the behavior I want. Finally, the third positional argument is `y`. Actually, I just checked the documentation, `y` is actually a named argument. I should specifically call it out in my call. I'll fix that. `y` is another array-like object that holds the target variable to predict. `cv` is a named argument, that if an integer (like 20), then `cross_val_score()` calls a `cv`-Fold Cross-Validation. `cross_val_score()` returns an ndarray of size (`cv`,) holding the scores returned for the cross-validation. In my method, `test_classify()`, `scores.mean()` is calling an internal method from an ndarray to return the arithmetic mean of the values in the array.

In [94]:
testa = np.linspace(1, 25, 25).reshape(5,5)

In [95]:
testa

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [96]:
testb = np.array([False, True, True, False, True])
testb

array([False,  True,  True, False,  True])

So if I slice `testa` with `testb`, it should return the columns starting with 2, 3, and 5.

In [97]:
testa[:, testb]

array([[ 2.,  3.,  5.],
       [ 7.,  8., 10.],
       [12., 13., 15.],
       [17., 18., 20.],
       [22., 23., 25.]])

Good! Additionally, according to the numpy documentation, slicing returns a view of the original array, not a copy. Thus, I should be careful not to edit anything. However, `cross_val_score()` does not edit the data, it only analyzes it and returns its own results in a separate array. So I'm satisfied with this.

`final_scores()` is essentially identical to `test_classify()`. I double checked that the variables were all correct, it should be good.

The only thing left is `execute_search()`. This is difficult to test. I'll walk through the code line by line to make sure the algorithm is doing what I want, and then I'll step it through a couple time steps, one step at a time to see where it's going.

Okay, here we go.

**Lines 24-25:** sets up the for loop and updates the time variable. This for loop steps the entire swarm through time. Each iteration is one step in time. Each step, the swarm must:

* move
* check fitness
* update best positions

It runs from t=1 (t=0 is initial state) until the maximum time specified in the second (max) argument of `t_bounds`. This means that the time variable is stepped forward, *Then* the state is updated. So if I want to report the state of the swarm at t, then the reporting needs to happen at the end of the loop.

**Line 26:** sets up the second for loop. This for loop steps through every particle in the swarm. Each iteration is one particle moving through one step in time. For each step, the next particle must:

* update inertia
* update velocity
* update position
* report best variables

The loop runs through every `p` (particle) in `swarm`. Oops, that should be `self.swarm`. I'll change it.

**Lines 27-30:** These lines call the current particle's update methods. These should be in the correct order. The convert to binary method depends on an updated position. The position equation depends on an updated velocity. The velocity equation depends on an updated inertia. The inertia equation depends on the previous particle binary position and the previous global best binary position. So, the order of update should be:

1. Previous time step's particle's `pbinary` and swarm's `gbinary`.
2. Inertia
3. Velocity
4. Position
5. Binary Position.

Which is definitely the case!

**Line 31:** This line calls the `eval-fitness()` method on the current particle's new binary position. It assigns it to the local variable, f. This allows the algorithm to perform multiple comparisons without recalculating every time.

**Lines 32-35:** This is an if statement. The condition for execution is that the current particle's current position fitness is better than the current particle's stored best fitness. If the new fitness is better, then the current position is better than the particle's stored best position. Thus, it should be updated. The next three lines update `pbest`, `pbinary`, and `p_fitness` with copies of the current values. This is VITAL that the stored state is updated with copies, NOT with recalculations. The binary vectors are calculated using a random value. Thus, identical positions may give different binary vectors. However, I want my algorithm to return a static, predictable value that can be mapped to the returned fitness and used in future research. So I need to know the exact binary vector that produced these results. Additionally, I want to reduce computational time so copying is better than recalculating.

**Lines 36-45:** This is a carbon copy of Lines 32-35 with one extra line. The comparison is with the swarm attribute, `g_fitness` (and associated state variables). The extra line is to update the counter. If `gbest` stagnates for 3 iterations, it is archived in abest and then shuffled (using the `shuffle_gbest()` method). The comment explains why the counter is set to -1 instead of 0.

**Lines 46-49:** This is similar to the two previous sections. It updates the archived best position/binary/fitness. However, it is Outside the particle for loop because it is only dependent on the global best of the entire swarm. Thus, rather than repeating it for every particle, this code waits until the global best is established, then performs a single check/update to save time.

**Line 50:** This line merely increments the `gbest_counter`. This should be done every time the swarm moves through a single time step.

**Lines 51-52:** This if statement tests for stagnation. If the global best has not changed in 3 iterations, it is archived into abest and then randomly reinitialized to add stochasticity and "shake up" the swarm's velocity. It also has a significant effect on the inertia. A conceptual manual step by step is below to check values of 0, -1, and 3 depending on where you are in the code.

### Double check for the stagnation values
#### Case 1: Stagnation
t = 0 (Initialization): counter is initialized at 0. gbest has existed *through* 0 updates of position (it was created after this first random positioning).

t = 1: counter is 0 at the beginning of the loop, counter is 1 at the end of the loop. At the check, gbest has not changed through 1 update of position (update from random init to t=1).

t = 2: counter is 1 at the beginning of the loop, gbest did not change, counter is 2 at the end of the loop. At the check, gbest has not changed through 2 updates of position.

t = 3: counter is 2 at the beginning of the loop, gbest did not change, counter is 3 at the end of the loop. At the check, gbest has not changed through 3 updates of position. Shuffle triggers. counter is 0 at the end of the loop. gbest has existed through 0 updates of position (it was just randomized).

t = 4: counter is 0 at the beginning of the loop, gbest did not change, counter is 1 at the end of the loop. At the check, gbest has not changed through 1 update of position.

------------------------------------------------------------------------------------

#### Case 2: Reset

t = 0 (Initialization): counter is initialized at 0. gbest has existed *through* 0 updates of position (it was created after this first random positioning).

t = 1: counter is 0 at the beginning of the loop, counter is 1 at the end of the loop. At the check, gbest has not changed through 1 update of position (update from random init to t=1).

t = 2: counter is 1 at the beginning of the loop, gbest did not change, counter is 2 at the end of the loop. At the check, gbest has not changed through 2 updates of position.

t = 3: counter is 2 at the beginning of the loop, gbest changes, counter is set to -1, counter is 0 (increment statement). At the check, gbest has not changed through 0 updates of position.

t = 4: counter is 0 at the beginning of the loop, gbest did not change, counter is 1 at the end of the loop. At the chekc, gbest has not changed through 1 update of position.

Good! This looks to be the type of behavior I'm looking for. I double checked that all the method arguments are coorect and that all the comparisons are comparing correclty. I think I trust this about as much as I can where I am the only evaluator. I'll step the swarm through a couple of time steps and do some sanity checks.

In [98]:
npart = 2
c1 = 2.1
c2 = 2.2
c3 = 2.3
ndim = 190
alpha = 0.5
test_size = 0.3
x_bounds = (-6.0, 6.0)
v_bounds = (-4.0, 0.25)
w_bounds = (0.4, 0.9)
t_bounds = (0, 3)
data_path = 'working_data/prepped_for_classifier/data.csv'
target_path = 'working_data/prepped_for_classifier/target.csv'

In [99]:
swarm = COMB_Swarm(npart, c1, c2, c3, ndim, alpha, test_size,
                   x_bounds, v_bounds, w_bounds, t_bounds,
                   data_path, target_path)

In [100]:
swarm.initialize_particles()

In [101]:
swarm.t_bounds

(0, 3)

In [102]:
swarm.t_bounds = (0, 2)

In [103]:
swarm.execute_search()

I missed a `self`.

In [104]:
swarm.t

1

In [105]:
swarm.swarm

In [106]:
swarm.g_fitness

0.7106037151702786

In [107]:
swarm.swarm[0].p_fitness

0.6527089783281734

In [108]:
swarm.swarm[1].p_fitness

0.7106037151702786

In [109]:
swarm.execute_search()

In [110]:
swarm.g_fitness

0.8002235982112144

In [111]:
swarm.swarm[0].p_fitness

0.7684984520123839

In [112]:
swarm.swarm[1].p_fitness

0.8002235982112144

All of that looks good. It looks like it's progressing. I think I'm going to do a run and see what happens.

In [113]:
npart = 100
c1 = 2.1
c2 = 2.1
c3 = 2.1
ndim = 190
alpha = 0.8
test_size = 0.3
x_bounds = (-6.0, 6.0)
v_bounds = (-4.0, 0.25)
w_bounds = (0.4, 0.9)
t_bounds = (0, 50)
data_path = 'working_data/prepped_for_classifier/data.csv'
target_path = 'working_data/prepped_for_classifier/target.csv'

In [114]:
# swarm = COMB_Swarm(npart, c1, c2, c3, ndim, alpha, test_size,
#                    x_bounds, v_bounds, w_bounds, t_bounds,
#                    data_path, target_path)

In [115]:
# swarm.initialize_particles()

In [116]:
# swarm.execute_search()

At some point, for some reason, the eval_fitness method got passed a binary array with all False. I'm going to add some code to check for that and stop cleanly so that I can investigate.

In [117]:
# swarm = COMB_Swarm(npart, c1, c2, c3, ndim, alpha, test_size,
#                    x_bounds, v_bounds, w_bounds, t_bounds,
#                    data_path, target_path)

In [118]:
# swarm.initialize_particles()

In [119]:
# swarm.execute_search()

The same error happened and my code didn't trigger so I didn't ID the bug correctly. I'll leave the detection code in though. Maybe the array with 0 features is in the data arrays, not the subset?

In [120]:
swarm.X_train

array([[5.610e+00, 3.710e+00, 9.700e-01, ..., 1.890e+00, 0.000e+00,
        8.200e-01],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 4.880e+00, 0.000e+00,
        0.000e+00],
       [8.440e+00, 4.490e+00, 9.000e-01, ..., 2.820e+00, 2.030e+00,
        3.890e+00],
       ...,
       [1.176e+01, 1.040e+01, 5.000e-02, ..., 5.850e+00, 8.633e+01,
        3.100e+00],
       [0.000e+00, 9.400e-01, 7.700e-01, ..., 0.000e+00, 2.220e+00,
        0.000e+00],
       [1.690e+00, 3.420e+00, 2.300e-01, ..., 2.410e+00, 8.830e+00,
        1.810e+00]])

In [121]:
swarm.y_train

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0], dtype=int8)

In [122]:
swarm.y_train.shape

(179,)

In [123]:
swarm.t

1

Dang it, I messed up my error reporter. `np.count_nonzero()` returns number of `True` values in the array. So it should trigger if it is equal to 0, not `self.ndim`. I'll fix and try again.

In [124]:
# swarm = COMB_Swarm(npart, c1, c2, c3, ndim, alpha, test_size,
#                    x_bounds, v_bounds, w_bounds, t_bounds,
#                    data_path, target_path)

In [125]:
# swarm.initialize_particles()

In [126]:
# swarm.execute_search()

In [127]:
# swarm.swarm[92].b

In [128]:
# swarm.swarm[92].x

I think I know what's happening. b is constructed from a sigmoid function and a randomly chosen comparison number. Thus, it is totally feasible, especially given a large swarm/end time for a binary vector to accidentally become all False. However, this breaks the classifier. So, I should add code to catch this case in the fitness function where if an all False array is given, the fitness is 0.

In [129]:
swarm = COMB_Swarm(npart, c1, c2, c3, ndim, alpha, test_size,
                   x_bounds, v_bounds, w_bounds, t_bounds,
                   data_path, target_path)

In [130]:
swarm.initialize_particles()

In [131]:
swarm.execute_search()

In [132]:
swarm.t

49

In [133]:
swarm.a_fitness

0.8187272101823185

In [134]:
np.count_nonzero(swarm.abinary)

2

In [136]:
swarm.final_eval()

In [139]:
swarm.final_scores

array([0.66666667, 0.66666667, 0.55555556, 0.625     , 0.57142857,
       0.71428571, 0.71428571, 0.57142857, 0.71428571, 0.71428571])

In [137]:
swarm.final_scores.mean()

0.6513888888888889

In [138]:
from sklearn.model_selection import cross_val_score

In [143]:
test = cross_val_score(swarm.clf, swarm.X_train[:, swarm.abinary], swarm.y_train, cv=10)

In [144]:
test

array([0.84210526, 0.66666667, 0.88888889, 0.83333333, 0.77777778,
       0.83333333, 0.72222222, 0.66666667, 0.76470588, 0.76470588])

In [147]:
swarm.clf.fit(swarm.X_train[:, swarm.abinary], swarm.y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [148]:
swarm.clf.score(swarm.X_test[:, swarm.abinary], swarm.y_test)

0.7272727272727273

In [151]:
swarm2 = COMB_Swarm(npart, c1, c2, c3, ndim, alpha, test_size,
                   x_bounds, v_bounds, w_bounds, t_bounds,
                   data_path, target_path)

In [152]:
swarm2.initialize_particles()

In [153]:
swarm2.execute_search()

In [156]:
swarm2.a_fitness

0.8148882008943928

In [155]:
np.count_nonzero(swarm2.abinary)

2

In [157]:
swarm2.clf.fit(swarm2.X_train[:, swarm2.abinary], swarm2.y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [159]:
swarm2.clf.score(swarm2.X_train[:, swarm2.abinary], swarm2.y_train)

0.8324022346368715

In [158]:
swarm2.clf.score(swarm2.X_test[:, swarm2.abinary], swarm2.y_test)

0.6753246753246753

Well, in both test cases, no obvious errors occurred and the model Way overfit to the training data. Only giving back a 2 features that did better than 80% accuracy on the training data and as good or worse than the baseline for the test data.

I think I'm done with this notebook. The code appears to run correctly and actual experiments can be done in other scripts or notebooks.