In [1]:
import numpy as np
from sklearn import svm
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate

In [2]:
iris = datasets.load_iris()

In [3]:
type(iris)

sklearn.utils.Bunch

In [6]:
dir(iris)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [9]:
print(iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [29]:
print(type(iris.data))
print(iris.data.shape)
print(iris.data[:5, :])

<class 'numpy.ndarray'>
(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [26]:
print(type(iris.feature_names))
print(len(iris.feature_names))
print(iris.feature_names)

<class 'list'>
4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [24]:
print(type(iris.target))
print(iris.target.shape)
print(iris.target)

<class 'numpy.ndarray'>
(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [17]:
print(type(iris.target_names))
print(iris.target_names.shape)
print(iris.target_names)

<class 'numpy.ndarray'>
(3,)
['setosa' 'versicolor' 'virginica']


In [32]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.3, random_state = 12)

In [30]:
clf = svm.SVC()

In [33]:
clf.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [34]:
clf.score(X_test, y_test)

0.9777777777777777

In [37]:
scores = cross_val_score(clf, iris.data, iris.target, cv=10)

In [39]:
print(scores)
print(scores.mean())
print(scores.std())

[1.         0.93333333 1.         1.         1.         0.93333333
 0.93333333 1.         1.         1.        ]
0.9800000000000001
0.030550504633038926


In [44]:
clf.score(X_test, y_test)

0.9777777777777777

In [41]:
import pandas as pd

In [42]:
df = pd.read_csv('working_data/Neurite_Total_Length_Input.csv')

In [43]:
df.head()

Compound Name  Stratified screen category (1=hit, 0=non-hit)  \
0                ASP3026                                              1   
1              Bafetinib                                              1   
2  Bisindolylmaleimide I                                              1   
3             EMD1214063                                              1   
4    Flt-3 Inhibitor III                                              1   

     ABL1    ABL2   AKT1   AKT2    AKT3     ALK  AURKA  AURKB  ...      TEK  \
0  22.025  15.450  0.000  0.990   2.985  92.700  7.445  0.175  ...    3.555   
1  94.970  91.785  0.000  0.000   2.115   1.945  0.000  1.280  ...    1.175   
2   0.000   0.000  0.000  1.080  12.670   2.790  0.000  3.790  ...    0.300   
3   0.000   0.000  1.925  2.565   0.000   3.255  0.000  5.020  ...    0.000   
4  36.300  15.345  0.000  1.320   0.000   1.670  0.000  8.850  ...    1.800   

     TNK2  TSSK1B  TSSK2    TTK    TXK   TYK2  TYRO3    YES1  ZAP70  
0  88.590  32.070  6.055  1.210  3.300  0.000  0.165  62.310    0.0  
1   0.000  10.880  2.240  0.000  6.445  0.000  0.000  39.890    0.0  
2   0.000   1.855  0.000  0.000  0.000  5.605  5.685   3.090    0.0  
3   0.000   0.000  1.200  0.000  2.455  2.470  6.325   2.795    0.0  
4   1.675   0.000  0.720  3.485  1.000  5.855  7.795  19.750    0.0  

[5 rows x 192 columns]

In [50]:
target = df['Stratified screen category (1=hit, 0=non-hit)']
print(type(target))
target.to_csv('working_data/target.csv', sep=',', index=False)

<class 'pandas.core.series.Series'>


In [53]:
test = np.loadtxt('working_data/target.csv', delimiter=',', dtype=np.int8)

In [54]:
test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [57]:
df.drop(['Compound Name', 'Stratified screen category (1=hit, 0=non-hit)'],
        axis=1, inplace=True)

In [58]:
df.head()

ABL1    ABL2   AKT1   AKT2    AKT3     ALK  AURKA  AURKB  AURKC     AXL  \
0  22.025  15.450  0.000  0.990   2.985  92.700  7.445  0.175    0.0   4.685   
1  94.970  91.785  0.000  0.000   2.115   1.945  0.000  1.280    0.0   0.000   
2   0.000   0.000  0.000  1.080  12.670   2.790  0.000  3.790    0.0   0.000   
3   0.000   0.000  1.925  2.565   0.000   3.255  0.000  5.020    0.0  16.875   
4  36.300  15.345  0.000  1.320   0.000   1.670  0.000  8.850    0.0   2.150   

   ...      TEK    TNK2  TSSK1B  TSSK2    TTK    TXK   TYK2  TYRO3    YES1  \
0  ...    3.555  88.590  32.070  6.055  1.210  3.300  0.000  0.165  62.310   
1  ...    1.175   0.000  10.880  2.240  0.000  6.445  0.000  0.000  39.890   
2  ...    0.300   0.000   1.855  0.000  0.000  0.000  5.605  5.685   3.090   
3  ...    0.000   0.000   0.000  1.200  0.000  2.455  2.470  6.325   2.795   
4  ...    1.800   1.675   0.000  0.720  3.485  1.000  5.855  7.795  19.750   

   ZAP70  
0    0.0  
1    0.0  
2    0.0  
3    0.0  
4    0.0  

[5 rows x 190 columns]

In [62]:
mylist = list(df.columns)
import csv

with open('feature_names.csv', 'w') as myfile:
    wr = csv.writer(myfile)
    wr.writerow(mylist)

In [63]:
target_names = np.loadtxt('feature_names.csv', dtype=str, delimiter=',')

In [64]:
target_names

array(['ABL1', 'ABL2', 'AKT1', 'AKT2', 'AKT3', 'ALK', 'AURKA', 'AURKB',
       'AURKC', 'AXL', 'BLK', 'BMX', 'BRAF', 'BRSK1', 'BRSK2', 'BTK',
       'CAMK1D', 'CAMK2A', 'CAMK2D', 'CAMK4', 'CDC42BPA', 'CDC42BPB',
       'CDK1', 'CDK2', 'CDK3', 'CDK4', 'CDK5', 'CDK6', 'CHEK1', 'CHEK2',
       'CHUK', 'CLK2', 'CLK3', 'CSF1R', 'CSK', 'CSNK1A1', 'CSNK1G1',
       'CSNK1G2', 'CSNK1G3', 'DAPK1', 'DCLK2', 'DDR2', 'DYRK1A', 'DYRK1B',
       'DYRK2', 'EGFR', 'EPHA2', 'EPHA3', 'EPHA4', 'EPHB2', 'EPHB3',
       'EPHB4', 'ERBB2', 'ERBB4', 'FER', 'FES', 'FGFR1', 'FGFR2', 'FGFR3',
       'FGFR4', 'FGR', 'FLT1', 'FLT3', 'FLT4', 'FRK', 'FYN', 'GRK6',
       'GSK3A', 'GSK3B', 'HCK', 'HIPK1', 'IGF1R', 'IKBKB', 'IKBKE',
       'INSR', 'INSRR', 'IRAK4', 'ITK', 'JAK1', 'JAK2', 'JAK3', 'KDR',
       'KIT', 'LCK', 'LRRK2', 'LTK', 'LYN', 'MAP2K1', 'MAP4K2', 'MAP4K4',
       'MAPK1', 'MAPK11', 'MAPK12', 'MAPK13', 'MAPK14', 'MAPK3', 'MAPK9',
       'MAPKAPK2', 'MAPKAPK3', 'MAPKAPK5', 'MARK1', 'MARK2', 'MARK3',
 

In [66]:
df.head()

ABL1    ABL2   AKT1   AKT2    AKT3     ALK  AURKA  AURKB  AURKC     AXL  \
0  22.025  15.450  0.000  0.990   2.985  92.700  7.445  0.175    0.0   4.685   
1  94.970  91.785  0.000  0.000   2.115   1.945  0.000  1.280    0.0   0.000   
2   0.000   0.000  0.000  1.080  12.670   2.790  0.000  3.790    0.0   0.000   
3   0.000   0.000  1.925  2.565   0.000   3.255  0.000  5.020    0.0  16.875   
4  36.300  15.345  0.000  1.320   0.000   1.670  0.000  8.850    0.0   2.150   

   ...      TEK    TNK2  TSSK1B  TSSK2    TTK    TXK   TYK2  TYRO3    YES1  \
0  ...    3.555  88.590  32.070  6.055  1.210  3.300  0.000  0.165  62.310   
1  ...    1.175   0.000  10.880  2.240  0.000  6.445  0.000  0.000  39.890   
2  ...    0.300   0.000   1.855  0.000  0.000  0.000  5.605  5.685   3.090   
3  ...    0.000   0.000   0.000  1.200  0.000  2.455  2.470  6.325   2.795   
4  ...    1.800   1.675   0.000  0.720  3.485  1.000  5.855  7.795  19.750   

   ZAP70  
0    0.0  
1    0.0  
2    0.0  
3    0.0  
4    0.0  

[5 rows x 190 columns]

In [67]:
df.to_csv('working_data/data.csv', sep=',', header=False, index=False)

In [68]:
data = np.loadtxt('working_data/data.csv', delimiter=',', dtype=np.float64)

In [69]:
data

array([[22.025, 15.45 ,  0.   , ...,  0.165, 62.31 ,  0.   ],
       [94.97 , 91.785,  0.   , ...,  0.   , 39.89 ,  0.   ],
       [ 0.   ,  0.   ,  0.   , ...,  5.685,  3.09 ,  0.   ],
       ...,
       [ 3.73 ,  4.64 ,  0.26 , ...,  3.72 ,  2.41 ,  0.   ],
       [ 8.44 ,  4.49 ,  0.9  , ...,  2.82 ,  2.03 ,  3.89 ],
       [ 0.   ,  0.16 ,  0.   , ...,  2.21 ,  3.03 ,  0.   ]])

In [71]:
target = test

In [72]:
target

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [73]:
KX_train, KX_test, Ky_train, Ky_test = train_test_split(data, target, test_size = 0.3, random_state = 12)

In [74]:
Kclf = svm.SVC()

In [75]:
Kclf.fit(KX_train, Ky_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [77]:
Kclf.score(KX_test, Ky_test)

0.7272727272727273

In [78]:
Kscores = cross_val_score(Kclf, data, target, cv=10)
print(Kscores)
print(Kscores.mean())
print(Kscores.std())

[0.7037037  0.7037037  0.73076923 0.73076923 0.72       0.72
 0.72       0.72       0.72       0.72      ]
0.7188945868945869
0.008665286073402657
